version: '3.8'
services:
  app:
    container_name: app
    build: ./
    restart: always
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/usr/src/app
    depends_on:
      - db
    networks:
      - app-bridge
    environment:
      PORT: ${PORT}
      DB_URL: ${DB_URL}
    command: npm run start:dev

  db:
    container_name: db
    image: postgres:14.2-alpine3.15
    restart: always
    environment:
      POSTGRES_DB: ${DB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./db/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
      - local-pgdata:/var/lib/posgresql/data
    networks:
      - app-bridge

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - ${PGADMIN_PORT}:80
    volumes:
      - local-pgadmin:/var/lib/pgadmin
    networks:
      - app-bridge
    depends_on:
      - db

volumes:
  local-pgdata:
  local-pgadmin:

networks:
  app-bridge:
    driver: bridge
